name: 'Daily Job(freetv)'

on:
  schedule:
    - cron: '45 23 * * *'  # 每天UTC时间23:45运行
  workflow_dispatch:
    inputs:
      environment:
        description: 'Daily Job(freetv)'
        required: true
        default: 'production'

jobs:
  run_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Run Python script
      run: python assets/freetv/freetv.py
          
    - name: Commit changes
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add assets/freetv/freetv_output.txt
          git add assets/freetv/freetv_output_cctv.txt
          git add assets/freetv/freetv_output_ws.txt
          git add assets/freetv/freetv_output_other.txt
          git commit -m ":tv:  (Freetv)AutoUpdate $(date -d "+8 hours" +'%Y%m%d')"

          current_datetime=$(date +"%Y%m%d_%H%M%S")
          # cp assets/freetv/freetv_output.txt history/freetv/"${current_datetime}_freetv_output.txt"
          # git add history/freetv/"${current_datetime}_freetv_output.txt"
          # git commit -m "(freetv)Archive file with timestamp"

          # 将归档文件打包zip文件
          zip_filename="${current_datetime}_freetv_output.zip"
          zip "history/freetv/${zip_filename}" assets/freetv/freetv_output.txt
          git add "history/freetv/${zip_filename}"
          git commit -m "(freetv) Archive file as ZIP with timestamp"
          
          
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
        
